api: /api/v1
frontEnd:
  Url: http://ec2-18-183-67-247.ap-northeast-1.compute.amazonaws.com:3000/
  domain: 18.183.67.247


spring:
  profiles:
    include: oauth2, db, cloud

server:
  servlet:
    session:
      cookie:
        domain: localhost
